/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import org.example.model.Persona;
import org.example.serialization.DeserializePersonaFromXML;
import org.example.serialization.SerializePersonaToJson;

public class App {

    public static void main(String[] args) throws IOException {
        runPersone();
    }

    private static void runPersone() throws IOException {
        List<Persona> persone = new DeserializePersonaFromXML().deserialize();
        String json = new SerializePersonaToJson().serialize(persone);
        Files.writeString(Path.of("persone.json"), json);
    }
}
